### ISSUE TITLE
No module name "solvent" in prep_solvent_absolute.py

### ISSUE THREAD

**Issue by mainguyenanhvu** [MobleyLab/SeparatedTopologies#18]
I do not know where is solvent module in your code. Please show me. Thank you.

**Comment by megosato** [comment]
@mainguyenanhvu So sorry for the delay, working on getting the repo updated, but in the meantime please try replacing line #2 `from SeparatedTopologies import solvent as so` with `from SeparatedTopologies import make_absolute_top_solvent as so`
